global b_Forward_request
global ul_Variable_name

#READ name1SWC
def Rte_Read_name1SWC_Variable_name():
    return ul_Variable_name
...
...
...

#READ name2SWC
def Rte_Read_name2SWC_Variable_name():
    return ul_Variable_name
...
...
...

#WRITE name1SWC
def Rte_Write_name1SWC_Forward_request(arg):
    b_Forward_request = arg
...
...
...

#WRITE name2SWC
def Rte_Write_name2SWC_Forward_request(arg):
    b_Forward_request = arg
...
...
...
    
