# This SWC is responsible for the Bazooka
# Sends shooting signal


# Autogenerated code, DO NOT EDIT
from RTE import Rte_Read_BazookaSWC_E_State, Rte_Write_BazookaSWC_b_Shoot
# End of autogenerated code

import uasyncio as asyncio
from typedefs import States

global async_timer
async_timer = 50 # this variable stores the time in ms that we use in asyncio.sleep

async def BazookaSWC():
    global async_timer
    previousState = States.NONE  # this variable stores the previos state of the robot (starts with NONE)
    while True: 
        state = Rte_Read_BazookaSWC_E_State() # this variable stores the current state of the robot gets the value from the RTE
        if state == States.SHOOT and previousState != States.SHOOT:
            Rte_Write_BazookaSWC_b_Shoot(1)
        previousState = state

        await asyncio.sleep_ms(async_timer)  # Adjust sleep time later if needed
