# Autogenerated code, DO NOT EDIT
from RTE import Rte_Read_EmergencySWC_b_Control_bits_valid, Rte_Read_EmergencySWC_f_Distance, Rte_Write_EmergencySWC_b_Emergency_distance, Rte_Write_EmergencySWC_b_Emergency_timeout
# End of autogenerated code

import uasyncio as asyncio

global emergency_bit
emergency_bit = 0

async def EmergencySWC():
    while True: 
        connectionTimedOut = Rte_Read_EmergencySWC_b_Control_bits_valid()
        distance = Rte_Read_EmergencySWC_f_Distance()
        global emergency_bit
        
        if distance < 10:    # this is already in cm, right?
            emergency_bit = 1
            Rte_Write_EmergencySWC_b_Emergency_distance(emergency_bit)
        
        if connectionTimedOut:      
            emergency_bit = 1
            Rte_Write_EmergencySWC_b_Emergency_timeout(emergency_bit)

        if emergency_bit == 1 and distance > 10 and not connectionTimedOut:
            emergency_bit = 0       
            Rte_Write_EmergencySWC_b_Emergency_distance(emergency_bit)
            Rte_Write_EmergencySWC_b_Emergency_timeout(emergency_bit)

        await asyncio.sleep_ms(50)  # Adjust sleep time later if needed
