# Autogenerated code, DO NOT EDIT
from RTE import Rte_Read_FaceProcessorSWC_S_face_position, Rte_Write_FaceProcessorSWC_S_face
# End of autogenerated code
import math

async def FaceProcessorSWC():

    while True:
        face_position = Rte_Read_FaceProcessorSWC_S_face_position()   # the face position struct


        if face_position[0]:
            #  scaling
            divisorHorizontal = face_position[1] / 255
            divisorVertical = face_position[2] / 255

            leftEyeX = face_position[9]
            leftEyeY = face_position[10]

            rightEyeX = face_position[11]
            rightEyeY = face_position[12]

            # distance between two eyes
            eyesDistanceSquared = pow(leftEyeX - rightEyeX, 2) + pow(leftEyeY - rightEyeY, 2)
            dist = math.sqrt(eyesDistanceSquared)     # the distance between eyes

            # scaling
            noseX = face_position[7]
            noseX = noseX / divisorHorizontal

            dist = dist / divisorHorizontal


            if face_position[0] == 1:   # enemy
                s_face = (1, noseX, dist)
            elif face_position[0] == 2:    # friend
                s_face = (2, noseX, dist)

            Rte_Write_FaceProcessorSWC_S_face(s_face)

        else:
            s_face = (0, 0, 0)
            Rte_Write_FaceProcessorSWC_S_face(s_face)




        await asyncio.sleep_ms(async_timer)