# this SWC is responsoble for the ultrasonc senzors functionility and conversion to the asked value

# Autogenerated code, DO NOT EDIT
from RTE import Rte_Read_UltrasonicSWC_si16_Raw_distance, Rte_Write_UltrasonicSWC_f_Distance
# End of autogenerated code

import uasyncio as asyncio

global async_timer
async_timer = 50 # this variable stores the time in ms that we use in asyncio.sleep


# Task to read ultrasonic sensor continuously
async def UltrasonicSWC():
    global async_timer
    while True: 
        distance = Rte_Read_UltrasonicSWC_si16_Raw_distance()   #It will read in mm 
        devide_forcm = 10  #the value we have to devide to get the distance in cm
        # Transfer to cm based on requirement:
        distance_cm = distance / devide_forcm # the distance converted to cm
        Rte_Write_UltrasonicSWC_f_Distance(distance_cm)
        
        await asyncio.sleep_ms(async_timer)  # Adjust sleep time as needed
